# Generated by Django 3.2.3 on 2021-06-02 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.IntegerField(choices=[(0, 'SHOT'), (1, 'DRINK'), (2, 'KOKTAJL')])),
                ('prepare', models.CharField(max_length=1048)),
                ('ingredients', models.CharField(max_length=1048)),
                ('kcal', models.IntegerField(default=0)),
                ('portion', models.IntegerField(default=0)),
                ('time_prepare', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('who_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
