# Generated by Django 3.2.3 on 2021-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkApp', '0002_drinkingredients_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('Shot', 'SHOT'), ('Drink', 'DRINK'), ('Koktajl', 'KOKTAJL')], max_length=128),
        ),
    ]
