# Generated by Django 3.2.3 on 2021-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkApp', '0003_alter_drink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='ingredient',
            field=models.ManyToManyField(to='DrinkApp.Ingredient'),
        ),
    ]
