# Generated by Django 3.2.3 on 2021-06-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkApp', '0004_drink_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='ingredients',
        ),
    ]
